name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: darwin
            goarch: amd64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.18.0'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: |
          go build -v -o crt_sh-${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: crt_sh-${{ matrix.goos }}-${{ matrix.goarch }}
          path: crt_sh-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: binaries

      - name: Rename Artifacts
        run: |
          for file in binaries/*; do
            if [[ -f "$file" ]]; then
              filename=$(basename "$file")
              new_filename="crt_sh_${filename##*-}"
              mv "$file" "binaries/$new_filename"
            fi
          done

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/**/*
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
