name: Go Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags matching vX.Y.Z

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.24'
          cache: 'true'

      - name: Build
        run: go build -v -o crtsh-go .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: crtsh-go # Customize artifact name
          path: ${{ github.workspace }} # Customize path to built artifact

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build # Depend on the build job
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: crtsh-go # Match artifact name from build job
          path: ${{ github.workspace }} # Match path from build job

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }} # Path to downloaded artifact
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
