name: Build and Release Go Binaries

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags matching vX.Y.Z

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: darwin
            goarch: amd64 #remove this line if you want to build for darwin amd64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.18.0'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build binaries
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o my-go-project-${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: my-go-project-${{ matrix.goos }}-${{ matrix.goarch }}
          path: my-go-project-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: binaries

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/**/*
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
