name: Go Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags matching vX.Y.Z

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
          cache: 'true'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-app # Customize artifact name
          path: ${{ github.workspace }}/app # Customize path to built artifact

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build # Depend on the build job
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: built-app # Match artifact name from build job
          path: ${{ github.workspace }}/app # Match path from build job

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/app/**/* # Path to downloaded artifact
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
